security_app:
  module: security
  class: SecurityAutomation
  entities:
    motion_sensors:
      - binary_sensor.bewegung_buero
      - binary_sensor.bewegung_schlafzimmer
      - binary_sensor.bewegung_ankleidezimmer
      - binary_sensor.bewegung_bad_klein
    door_sensors:
      - binary_sensor.fenster_wohnzimmer
      - binary_sensor.tuer_wohnzimmer_balkon
      - binary_sensor.fenster_buero
      - binary_sensor.fenster_bad_gross
      - binary_sensor.fenster_ankleidezimmer
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.tuer_kueche_balkon
      - binary_sensor.fenster_kueche
      - binary_sensor.tuer_wohnung
      - binary_sensor.tuer_buero
      - binary_sensor.tuer_ankleidezimmer
      - binary_sensor.tuer_bad_gross
      - binary_sensor.tuer_bad_klein
      - binary_sensor.tuer_schlafzimmer
      - binary_sensor.tuer_reduit
    alarm_lights:
      - light.ankleidezimmer

arm_when_everyone_gone:
  module: security
  class: ArmOnDeparture
  dependencies: 
    - presence_app
    - security_app

disarm_when_someone_home:
  module: security
  class: DisarmOnArrival
  dependencies:
    - presence_app
    - security_app

arm_disarm_when_cleaning:
  module: security
  class: ArmDisarmCleaning
  dependencies:
    - presence_app
    - security_app

notify_on_alarm_change:
  module: security
  class: NotificationOnChange
  dependencies:
    - presence_app
    - security_app
    - notification_app
  notifications:
    targets: Dimitri

notify_on_bad_login_attempt:
  module: security
  class: NotifyOnBadLoginAttempt
  dependencies:
    - notification_app
  notifications:
    targets: Dimitri

last_motion:
  module: security
  class: LastMotion
  entities:
    motion_sensors:
      - binary_sensor.bewegung_ankleidezimmer
      - binary_sensor.bewegung_bad_klein
      - binary_sensor.bewegung_buero
      - binary_sensor.bewegung_schlafzimmer