#################################################
################ Binary Sensors #################
#################################################

#################################################
# Door/Window sensors
#################################################
binary_sensor.tuer_wohnung:
  friendly_name: Wohnung
  device_class: door
  icon: mdi:door
binary_sensor.tuer_bad_gross:
  friendly_name: Grosses Bad
  device_class: door
  icon: mdi:door
binary_sensor.tuer_bad_klein:
  friendly_name: Kleines Bad
  device_class: door
  icon: mdi:door
binary_sensor.tuer_buero:
  friendly_name: Büro
  device_class: door
  icon: mdi:door
binary_sensor.tuer_kueche_balkon:
  friendly_name: Küche
  device_class: door
  icon: mdi:door
binary_sensor.tuer_reduit:
  friendly_name: Reduit
  device_class: door
  icon: mdi:door
binary_sensor.tuer_schlafzimmer:
  friendly_name: Schlafzimmer
  device_class: door
  icon: mdi:door
binary_sensor.tuer_ankleidezimmer:
  friendly_name: Ankleide
  device_class: door
  icon: mdi:door
binary_sensor.tuer_wohnzimmer_balkon:
  friendly_name: Wohnzimmer
  device_class: door
  icon: mdi:door
binary_sensor.fenster_ankleidezimmer:
  friendly_name: Ankleide
  device_class: window
  icon: mdi:window-closed-variant
binary_sensor.fenster_bad_gross:
  friendly_name: Grosses Bad
  device_class: window
  icon: mdi:window-closed-variant
binary_sensor.fenster_buero:
  friendly_name: Büro
  device_class: window
  icon: mdi:window-closed-variant
binary_sensor.fenster_kueche:
  friendly_name: Küche
  device_class: window
  icon: mdi:window-closed-variant
binary_sensor.fenster_schlafzimmer:
  friendly_name: Schlafzimmer
  device_class: window
  icon: mdi:window-closed-variant
binary_sensor.fenster_wohnzimmer:
  friendly_name: Wohnzimmer
  device_class: window
  icon: mdi:window-closed-variant
#################################################
# Motion sensors
#################################################
binary_sensor.bewegung_ankleidezimmer:
  friendly_name: Ankleide
  device_class: motion
  icon: mdi:walk
binary_sensor.bewegung_bad_klein:
  friendly_name: Kleines Bad
  device_class: motion
  icon: mdi:walk
binary_sensor.bewegung_buero:
  friendly_name: Büro
  device_class: motion
  icon: mdi:walk
binary_sensor.bewegung_schlafzimmer:
  friendly_name: Schlafzimmer
  device_class: motion
  icon: mdi:walk
binary_sensor.bewegung_wohnzimmer:
  friendly_name: Wohnzimmer
  device_class: motion
  icon: mdi:walk

#################################################
################ Device Trackers ################
#################################################

#################################################
# Unifi integration Availability
#################################################
device_tracker.ap_wohnzimmer:
  friendly_name: Access Point
  icon: mdi:router-wireless
device_tracker.usg_router:
  friendly_name: USG Router
  icon: mdi:wan
device_tracker.switch_wohnzimmer:
  friendly_name: USW Wohnzimmer
  icon: mdi:network-router
device_tracker.switch_reduit:
  friendly_name: USW Reduit
  icon: mdi:network-router
device_tracker.nas:
  friendly_name: NAS
  icon: mdi:nas
device_tracker.server_nuc:
  friendly_name: NUC
  icon: mdi:server-network
device_tracker.raspberrypi:
  friendly_name: Unifi Controller
  icon: mdi:fruit-grapes
device_tracker.pi_ankleidezimmer:
  friendly_name: Ankleide
  icon: mdi:fruit-grapes
device_tracker.pi_buero:
  friendly_name: Büro
  icon: mdi:fruit-grapes
device_tracker.pi_wohnzimmer:
  friendly_name: Wohnzimmer
  icon: mdi:fruit-grapes
device_tracker.pi_schlafzimmer:
  friendly_name: Schlafzimmer
  icon: mdi:fruit-grapes
device_tracker.pc_sabrina:
  friendly_name: PC Sabrina
  icon: mdi:desktop-tower-monitor
device_tracker.pc_dimitri:
  friendly_name: PC Dimitri
  icon: mdi:desktop-tower-monitor
device_tracker.desktop_7a2lv3k:
  friendly_name: Laptop
  icon: mdi:laptop
device_tracker.dimitri_phone_unifi:
  friendly_name: Handy Dimitri
  icon: mdi:cellphone-android
device_tracker.sabrina_phone:
  friendly_name: Handy Sabrina
  icon: mdi:cellphone-android
device_tracker.ipad:
  friendly_name: iPad
  icon: mdi:tablet
device_tracker.harmonyhub:
  friendly_name: Harmony Hub
  icon: mdi:remote
device_tracker.roomba_wohnzimmer:
  friendly_name: Staubsauger
  icon: mdi:robot-vacuum
device_tracker.switch_entfeuchter:
  friendly_name: Entfeuchter
  icon: mdi:power-plug
device_tracker.minix_wohnzimmer:
  friendly_name: Kodi
  icon: mdi:play-network
device_tracker.musik_wohnzimmer:
  friendly_name: Wohnzimmer
  icon: mdi:speaker
device_tracker.musik_schlafzimmer:
  friendly_name: Schlafzimmer
  icon: mdi:speaker
device_tracker.musik_buero:
  friendly_name: Receiver Büro
  icon: mdi:speaker
#################################################
# Android App integration
#################################################
device_tracker.dimitri_phone_app:
  friendly_name: Handy Dimitri App
  icon: mdi:map-marker
#################################################
# MQTT integration
#################################################
device_tracker.dimitri_schluessel:
  friendly_name: Schlüssel Dimitri
  icon: mdi:key-wireless
device_tracker.sabrina_schluessel:
  friendly_name: Schlüssel Sabrina
  icon: mdi:key-wireless

#################################################
################### Persons #####################
#################################################
person.dimitri:
  friendly_name: Dimitri
  entity_picture: /local/presence/dimitri_home.jpg
person.sabrina:
  friendly_name: Sabrina
  entity_picture: /local/presence/sabrina_home.jpg

#################################################
################### Z-Wave ######################
#################################################
zwave.aeotec_zw090_zstick_gen5_eu:
  friendly_name: Aeotec Z-Wave Stick
  icon: mdi:z-wave
zwave.aeotec_zw100_multisensor_6:
  friendly_name: Aeotec Multi Ankleide
  icon: mdi:z-wave
zwave.aeotec_zw100_multisensor_6_10:
  friendly_name: Aeotec Multi kleines Bad
  icon: mdi:z-wave
zwave.aeotec_zw100_multisensor_6_11:
  friendly_name: Aeotec Multi Schlafzimmer
  icon: mdi:z-wave
zwave.aeotec_zw100_multisensor_6_4:
  friendly_name: Aeotec Multi Büro
  icon: mdi:z-wave

#################################################
################### Lights ######################
#################################################
light.ankleidezimmer:
  friendly_name: Deckenlampe
  icon: mdi:ceiling-light
light.buero:
  friendly_name: Deckenlampe
  icon: mdi:ceiling-light
light.stehlampe_wohnzimmer_vorne:
  friendly_name: Vorne
  icon: mdi:floor-lamp
light.stehlampe_wohnzimmer_hinten:
  friendly_name: Hinten
  icon: mdi:floor-lamp
light.decke_schlafzimmer:
  friendly_name: Deckenlampe
  icon: mdi:ceiling-light
light.kugellampe_schlafzimmer:
  friendly_name: Kugellampe
  icon: mdi:lamp

#################################################
################## Switches #####################
#################################################
switch.schalter_entfeuchter:
  friendly_name: Entfeuchter
  icon: mdi:fan

#################################################
###################  Sensors ####################
#################################################

#################################################
# Temperature sensors
#################################################
sensor.temperatur_ankleidezimmer:
  friendly_name: Ankleide
  icon: mdi:thermometer
sensor.temperatur_Schlafzimmer:
  friendly_name: Schlafzimmer
  icon: mdi:thermometer
sensor.temperatur_buero:
  friendly_name: Büro
  icon: mdi:thermometer
sensor.temperatur_wohnzimmer:
  friendly_name: Wohnzimmer
  icon: mdi:thermometer
sensor.temperatur_bad_klein:
  friendly_name: Kleines Bad
  icon: mdi:thermometer
sensor.synology_dsm_temperature_sda:
  friendly_name: NAS HDD 1
  icon: mdi:thermometer
sensor.synology_dsm_temperature_sdb:
  friendly_name: NAS HDD 2
  icon: mdi:thermometer
#################################################
# Humidity sensors
#################################################
sensor.luftfeuchtigkeit_schlafzimmer:
  friendly_name: Schlafzimmer
  icon: mdi:water-percent
sensor.luftfeuchtigkeit_bad_klein:
  friendly_name: Kleines Bad
  icon: mdi:water-percent
sensor.luftfeuchtigkeit_buero:
  friendly_name: Büro
  icon: mdi:water-percent
sensor.luftfeuchtigkeit_ankleidezimmer:
  friendly_name: Ankleide
  icon: mdi:water-percent
#################################################
# Lux sensors
#################################################
sensor.lux_schlafzimmer:
  friendly_name: Schlafzimmer
  icon: mdi:weather-sunny
sensor.lux_bad_klein:
  friendly_name: Kleines Bad
  icon: mdi:weather-sunny
sensor.lux_buero:
  friendly_name: Büro
  icon: mdi:weather-sunny
sensor.lux_ankleidezimmer:
  friendly_name: Ankleide
  icon: mdi:weather-sunny
sensor.lux_wohnzimmer:
  friendly_name: Wohnzimmer
  icon: mdi:weather-sunny
#################################################
# Battery sensors
#################################################
sensor.bad_klein_multisensor_battery:
  friendly_name: Kleines Bad

sensor.dimmschalter_ankleidezimmer_battery_level:
  friendly_name: Ankleide
sensor.dimmschalter_buero_battery_level:
  friendly_name: Büro
sensor.dimmschalter_sabrina_battery_level:
  friendly_name: Bett Sabrina
sensor.dimmschalter_schlafzimmer_battery_level:
  friendly_name: Schlafzimmer
sensor.dimmschalter_schlafzimmer_master_battery_level:
  friendly_name: Bett Dimitri
sensor.dimmschalter_wohnzimmer_battery_level:
  friendly_name: Wohnzimmer

sensor.fenster_ankleidezimmer_battery_level:
  friendly_name: Ankleide
sensor.fenster_bad_gross_battery_level:
  friendly_name: Grosses Bad
sensor.fenster_buero_battery_level:
  friendly_name: Büro
sensor.fenster_kueche_battery_level:
  friendly_name: Küche
sensor.fenster_schlafzimmer_battery_level:
  friendly_name: Schlafzimmer
sensor.fenster_wohnzimmer_battery_level:
  friendly_name: Wohnzimmer
sensor.tuer_ankleidezimmer_battery_level:
  friendly_name: Ankleide
sensor.tuer_bad_gross_battery_level:
  friendly_name: Grosses Bad
sensor.tuer_bad_klein_battery_level:
  friendly_name: Kleines Bad
sensor.tuer_buero_battery_level:
  friendly_name: Büro
sensor.tuer_kueche_balkon_battery_level:
  friendly_name: Küche Balkon
sensor.tuer_reduit_battery_level:
  friendly_name: Reduit
sensor.tuer_schlafzimmer_battery_level:
  friendly_name: Schlafzimmer
sensor.tuer_wohnung_battery_level:
  friendly_name: Wohnung
sensor.tuer_wohnzimmer_balkon_battery_level:
  friendly_name: Wohnzimmer

sensor.bewegung_wohnzimmer_battery_level:
  friendly_name: Wohnzimmer
#################################################
################  Media Player ##################
#################################################

#################################################
# Temperature sensors
#################################################
media_player.buero_musik_main:
  friendly_name: Yamaha Stereo
  icon: mdi:speaker
media_player.denon_avr_wohnzimmer:
  friendly_name: Denon AVR
  icon: mdi:speaker
media_player.kodi_wohnzimmer:
  friendly_name: Kodi
  icon: mdi:play-network-outline
media_player.heos_5:
  friendly_name: Heos 5
  icon: mdi:speaker