# configurations for core
homeassistant: !include config/homeassistant.yaml
frontend:
  themes: !include_dir_named config/themes/
  javascript_version: latest
lovelace:
  mode: yaml
config:
http: !include config/http.yaml
history: !include config/history.yaml
recorder: !include config/recorder.yaml
logbook:
updater:
discovery:
conversation:
map:
sun:
system_health:

# configuration for components
automation: !include config/automations.yaml
deconz: !include config/components/deconz.yaml
influxdb: !include config/components/influxdb.yaml
mqtt: !include config/components/mqtt.yaml
notify: !include config/components/notify.yaml
shopping_list:
speedtestdotnet: !include config/components/speedtestdotnet.yaml
tts: !include config/components/tts.yaml
weather: !include config/components/darksky.yaml
zwave: !include config/components/zwave.yaml

logger:
  default: info
  logs:
    hoimeassistant.components.websocket_api: debug