homeassistant: !include config/homeassistant.yaml

# configurations for core
frontend:
  javascript_version: latest
config:
http: !include config/http.yaml
updater:
discovery:
conversation:
history:
  include:
    entities:
      - input_select.dimitri_presence
      - input_select.sabrina_presence
      - input_select.house_presence
      - input_boolean.charging_phone_sabrina
      - input_boolean.charging_phone_dimitri
      - remote.wohnzimmer
      - group.all_lights
      - device_tracker.dimitri_pc
      - device_tracker.sabrina_pc
      - input_select.last_motion
      - input_boolean.sleep_mode
logbook:
map:
sun:
system_health:
lovelace:
  mode: yaml


# configuration for components
automation: !include config/automations.yaml
device_tracker: !include_dir_merge_list config/device_tracker
group: !include_dir_merge_named config/group
input_boolean: !include_dir_merge_named config/input_boolean
influxdb: !include config/components/influxdb.yaml
media_player: !include config/components/media_player.yaml
mqtt: !include config/components/mqtt.yaml
notify: !include config/components/notify.yaml
tts: !include config/components/tts.yaml
vacuum: !include config/components/roomba.yaml
weather: !include config/components/darksky.yaml
zwave: !include config/components/zwave.yaml
