sensor:
  # Battery Level of Multisensor
  - platform: template
    sensors:
      bad_klein_multisensor_battery:
        friendly_name: 'Bad klein Multisensor Batterie'
        value_template: >-
          {%- if states.zwave.aeotec_zw100_multisensor_6_10 -%}
            {{ states.zwave.aeotec_zw100_multisensor_6_10.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        device_class: battery
        entity_id: zwave.aeotec_zw100_multisensor_6_10


######## add google mini or similar later ##############