sensor:
  - platform: template
    sensors:
      tuer_bad_gross:
        value_template: '{% if states.binary_sensor.tuer_bad_gross %}
          {% if states.binary_sensor.tuer_bad_gross.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Tür Bad gross'

      fenster_bad_gross:
        value_template: '{% if states.binary_sensor.fenster_bad_gross %}
          {% if states.binary_sensor.fenster_bad_gross.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Fenster Bad gross'