sensor:
  - platform: template
    sensors:
      tuer_schlafzimmer:
        value_template: '{% if states.binary_sensor.tuer_schlafzimmer %}
          {% if states.binary_sensor.tuer_schlafzimmer.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Tür Schlafzimmer'

      fenster_schlafzimmer:
        value_template: '{% if states.binary_sensor.fenster_schlafzimmer %}
          {% if states.binary_sensor.fenster_schlafzimmer.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Fenster Schlafzimmer'
  - platform: template
    sensors:
      nacht_sensor:
        value_template: >-
            {% if strptime(states('sensor.time'), '%H:%M').hour<5 or strptime(states('sensor.time'), '%H:%M').hour>=23 %}
            nacht
            {% else %}
            tag
            {% endif %}
               
binary_sensor:
  - platform: bayesian
    prior: 0.25
    name: 'Dimitri Schläft'
    probability_threshold: 0.8
    observations:
        - entity_id: 'input_select.dimitri_presence'
          prob_given_true: 1.0
          prob_given_false: 0.56
          platform: 'state'
          to_state: 'Zu Hause'
        - entity_id: 'input_select.house_presence'
          prob_given_true: 0.0
          platform: 'state'
          to_state: 'Ferien'
        - entity_id: 'group.all_lights'
          prob_given_true: 1.0
          prob_given_false: 0.4
          platform: 'state'
          to_state: 'off'
        - entity_id: 'input_boolean.charging_phone_dimitri'
          prob_given_true: 0.95
          prob_given_false: 0.1
          platform: 'state'
          to_state: 'on'
        - entity_id: 'remote.wohnzimmer'
          prob_given_true: 1.0
          prob_given_false: 0.2
          platform: 'state'
          to_state: 'off'
        - entity_id: 'device_tracker.dimitri_pc'
          prob_given_true: 0.05
          prob_given_false: 0.18
          platform: 'state'
          to_state: 'home'
        - entity_id: 'sensor.nacht_sensor'
          prob_given_true: 0.7
          platform: 'state'
          to_state: 'on'

switch:
  - platform: mystrom
    host: !secret switch_dehumidifier_ip
    name: Schalter Entfeuchter

media_player:
  - platform: heos
    host: !secret heos_bedroom_ip
    name: HEOS Schlafzimmer

scene:
  - name: Gute Nacht
    entities:
      group.all_lights: 
        state: false
      switch.schalter_entfeuchter: 
        state: false
      remote.wohnzimmer: 
        state: false
      media_player.buero_musik_main: 
        state: false
      input_boolean.sleep_mode: 
        state: true
      script.play_good_night_list:
        state: true
  - name: Schlafzimmer alles aus
    entities:
      light.schlafzimmer: 
        state: false
      switch.schalter_entfeuchter:
        state: false
      media_player.heos_5:
        state: paused
script:
  play_good_night_list:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify
          source: "HEOS 5"
      - service: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: 0.07
      - service: media_player.play_media
        data:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DWSUFOo47GEsI'
          media_content_type: 'playlist'
      - service: media_player.shuffle_set
        data:
          entity_id: media_player.spotify
          shuffle: 'true'
      - service: media_player.media_next_track
        data:
          entity_id: media_player.spotify