#################################################
#################### Groups #####################
#################################################
group:
  ### All Lights (that are shown on the lights view)
  all_lighting:
    name: Alle Lichter
    entities:
      - light.ankleidezimmer
      - light.buero
      - light.decke_schlafzimmer
      - light.kugellampe_schlafzimmer
      - light.stehlampe_wohnzimmer_hinten
      - light.stehlampe_wohnzimmer_vorne

  ### All Devices (that are shown on the devices view)
  all_device_switches:
    name: Alle Geräte
    entities:
      - switch.schalter_entfeuchter
      - media_player.buero_musik_main
      - media_player.denon_avr_wohnzimmer
      - media_player.heos_5

  ### All Binary Sensors (door/window/motion/smoke/gas etc)
  all_binary_sensors:
    name: Alle Binärsensoren
    entities:
      - binary_sensor.bewegung_ankleidezimmer
      - binary_sensor.bewegung_bad_klein
      - binary_sensor.bewegung_buero
      - binary_sensor.bewegung_schlafzimmer
      - binary_sensor.bewegung_wohnzimmer
      - binary_sensor.fenster_ankleidezimmer
      - binary_sensor.fenster_bad_gross
      - binary_sensor.fenster_buero
      - binary_sensor.fenster_kueche
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.fenster_wohnzimmer
      - binary_sensor.tuer_kueche_balkon
      - binary_sensor.tuer_wohnung
      - binary_sensor.tuer_wohnzimmer_balkon

  all_physical_devices:
    name: Alle physischen Geräte
    entities:
      - zwave.aeotec_zw090_zstick_gen5_eu
      - zwave.aeotec_zw100_multisensor_6
      - zwave.aeotec_zw100_multisensor_6_10
      - zwave.aeotec_zw100_multisensor_6_11
      - zwave.aeotec_zw100_multisensor_6_4
      - light.decke_1_ankleidezimmer
      - light.decke_2_ankleidezimmer
      - light.decke_3_ankleidezimmer
      - light.decke_1_buero
      - light.decke_2_buero
      - light.decke_3_buero
      - light.decke_1_schlafzimmer
      - light.decke_3_schlafzimmer
      - light.decke_3_schlafzimmer
      - light.kugellampe_schlafzimmer
      - light.stehlampe_wohnzimmer_vorne
      - light.stehlampe_wohnzimmer_hinten
      - binary_sensor.fenster_wohnzimmer
      - binary_sensor.tuer_wohnzimmer_balkon
      - binary_sensor.fenster_buero
      - binary_sensor.fenster_bad_gross
      - binary_sensor.fenster_ankleidezimmer
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.tuer_kueche_balkon
      - binary_sensor.fenster_kueche
      - binary_sensor.tuer_wohnung
      - binary_sensor.tuer_buero
      - binary_sensor.tuer_ankleidezimmer
      - binary_sensor.tuer_bad_gross
      - binary_sensor.tuer_bad_klein
      - binary_sensor.tuer_schlafzimmer
      - binary_sensor.tuer_reduit
      - device_tracker.usg_router
      - device_tracker.switch_wohnzimmer
      - device_tracker.switch_reduit
      - device_tracker.ap_wohnzimmer
      - device_tracker.harmonyhub
      - device_tracker.minix_wohnzimmer
      - device_tracker.musik_buero
      - device_tracker.musik_schlafzimmer
      - device_tracker.musik_wohnzimmer
      - device_tracker.nas
      - device_tracker.pi_schlafzimmer
      - device_tracker.pi_ankleidezimmer
      - device_tracker.pi_wohnzimmer
      - device_tracker.pi_buero
      - device_tracker.roomba
      - device_tracker.raspberrypi
      - device_tracker.switch_entfeuchter

  ### Leave this group empty!! (DO NOT DELETE THIS)
  empty_group: 
    name: Empty Group
    entities:

  ### All Scenes (the way scenes work has been changed in the latest HA, this part is up for evaluation)
  all_scenes:
    name: All Scenes
    entities:
      - scene.buro_alles_aus

  ### All Temperature Sensors
  all_temperature_sensors:
    name: Alle Temperatursensoren
    entities:
      - sensor.temperatur_ankleidezimmer
      - sensor.temperatur_bad_klein
      - sensor.temperatur_buero
      - sensor.temperatur_schlafzimmer

  ### All Humidity Sensors
  all_humidity_sensors:
    name: Alle Luftfeuchtigkeitssensoren
    entities:
      - sensor.luftfeuchtigkeit_ankleidezimmer
      - sensor.luftfeuchtigkeit_bad_klein
      - sensor.luftfeuchtigkeit_buero
      - sensor.luftfeuchtigkeit_schlafzimmer

  # Light Groups
  ## Living Room
  ### RGB Lights
  livingroom_rgb_lights:
    name: Livingroom RGB Lights
    entities:
      - light.stehlampe_wohnzimmer_hinten
      - light.stehlampe_wohnzimmer_vorne
  ### Color Temperature Lights
  livingroom_color_temp_lights:
    name: Livingroom Color Temperature Lights
    entities:
  ### Other Lights
  livingroom_other_lights:
    name: Livingroom Other Lights
    entities:

  ## Bedroom
  ### RGB Lights
  bedroom_rgb_lights:
    name: Bedroom RGB Lights
    entities:
      - light.decke_schlafzimmer
      - light.kugellampe_schlafzimmer
  ### Color Temperature Lights
  bedroom_color_temp_lights:
    name: Bedroom Color Temperature Lights
    entities:
  ### Other Lights
  bedroom_other_lights:
    name: Bedroom Other Lights
    entities:

  ## Office
  ### RGB Lights
  office_rgb_lights:
    name: Office RGB Lights
    entities:
  ### Color Temperature Lights
  office_color_temp_lights:
    name: Office Color Temperature Lights
    entities:
      - light.buero
  ### Other Lights
  office_other_lights:
    name: Office Other Lights
    entities:

  ## Dressroom
  ### RGB Lights
  dress_room_rgb_lights:
    name: Dress Room RGB Lights
    entities:
      - light.ankleidezimmer  
  ### Color Temperature Lights
  dress_room_color_temp_lights:
    name: Hallway Color Temperature Lights
    entities:
  ### Other Lights
  dress_room_other_lights:
    name: Hallway Other Lights
    entities:


  # Device Groups
  ## Living Room
  ### Fans
  livingroom_fans:
    name: Wohnzimmer Lüfter
    entities:
  ### Devices
  livingroom_devices:
    name: Wohnzimmer Geräte
    entities:
      - media_player.denon_avr_wohnzimmer
      - media_player.kodi_wohnzimmer
      - remote.wohnzimmer

  ## Bedroom
  ### Fans
  bedroom_fans:
    name: Schlafzimmer Lüfter
    entities:
      - switch.schalter_entfeuchter
  ### Devices
  bedroom_devices:
    name: Schlafzimmer Geräte
    entities:
      - media_player.heos_5

  ## Office
  ### Fans
  office_fans:
    name: Büro Lüfter
    entities:
  ### Devices
  office_devices:
    name: Büro Geräte
    entities:
      - media_player.buero_musik_main

  ## Laundry Room
  ### Fans
  laundry_room_fans:
    name: Reduit Lüfter
    entities:
  ### Devices
  laundry_room_devices:
    name: Reduit Geräte
    entities:

  # Security Groups
  ### Camera's
  all_cameras:
    name: All Cameras
    entities:

  ### Window Sensors
  all_window_sensors:
    name: Alle Fenstersensoren
    entities:
      - binary_sensor.fenster_ankleidezimmer
      - binary_sensor.fenster_bad_gross
      - binary_sensor.fenster_buero
      - binary_sensor.fenster_kueche
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.fenster_wohnzimmer

  ### Door Sensors
  all_door_sensors:
    name: All Door Sensors
    entities:
      - binary_sensor.tuer_kueche_balkon
      - binary_sensor.tuer_wohnung
      - binary_sensor.tuer_wohnzimmer_balkon
      

  ### Motion Sensors
  all_motion_sensors:
    name: Alle Bewegungssensoren
    entities:
      - binary_sensor.bewegung_ankleidezimmer
      - binary_sensor.bewegung_bad_klein
      - binary_sensor.bewegung_buero
      - binary_sensor.bewegung_schlafzimmer
      - binary_sensor.bewegung_wohnzimmer

  ### Smoke Detectors
  all_smoke_detectors:
    name: All Smoke Detectors
    entities:

  ### All Motion, Smoke, Fire and Gas Sensors
  all_motion_smoke_sensors:
    name: All Motion Sensors
    entities:
      - binary_sensor.bewegung_ankleidezimmer
      - binary_sensor.bewegung_bad_klein
      - binary_sensor.bewegung_buero
      - binary_sensor.bewegung_schlafzimmer
      - binary_sensor.bewegung_wohnzimmer

  ### Persons
  all_persons:
    name: Alle Personen
    entities:
      - person.dimitri
      - person.sabrina

#################################################
################ Input Booleans #################
#################################################
input_boolean:
  # Other
  dummy1:
    initial: off
  dummy2:
    initial: off

  # Light Popup Options
  light_options:
    initial: off

#################################################
################# Input Select ##################
#################################################
input_select:
  # Frontend Greeting (shown in the header of the frontpage)
  frontend_greeting:
    name: Frontend Greeting
    options:
      - Guten Morgen
      - Gute Nacht
      - Guten Tag
      - Guten Abend

  # The theme selector used to show in the interface
  theme_selector:
    name: Theme Selector 
    options:
      - Silver
      - Space Gray
      - Sweet Pink
      - Valentine
      - Disable
      - Auto

  # Border Radius used in border-radius templates,
  # you can adjust border size to be selected here
  border_radius:
    name: Border Radius
    options:
      - 0px
      - 6px
      - 12px
      - 18px

  # Border Radius selector to show in the interface
  border_radius_selector:
    name: Border Radius Selector
    options:
      - None 
      - Small
      - Standard
      - Large

  # Box Shadow used in box-shadow templates, you can adjust
  # how the box shadow looks in here
  box_shadow:
    name: Box Shadow
    options:
      - none
      - 1px 1px 1px 0px rgba(0,0,0,0.75)
      - 2px 2px 2px 0px rgba(0,0,0,0.75)
      - 3px 3px 3px 0px rgba(0,0,0,0.75)
      - 5px 5px 5px 0px rgba(0,0,0,0.75)
  
  # Box Shadow selector to show in the interface
  box_shadow_selector:
    name: Box Shadow Selector
    options:
      - None
      - Small
      - Standard
      - Medium
      - Large

  # Person Menu 1 (used for personal views)
  person_menu_1:
    name: Person Menu 1 Selector
    options:
      - Übersicht
      - Auto
    initial: Übersicht

  # Person Menu 2 (used for personal views)
  person_menu_2:
    name: Person Menu 2 Selector
    options:
      - Übersicht
      - Standort
      - Zugverbindungen
    initial: Übersicht

  # Remote Control Selector
  remote_control:
    name: Remote Control Selector
    options:
      - Livingroom
      - Bedroom
    initial: Livingroom

  # Xiaomi Vacuum Selector
  xiaomi_vacuum:
    name: Xiaomi Vacuum
    options:
      - Quiet
      - Balanced
      - Turbo
      - Max
      - Mop

#################################################
################# Automations ###################
#################################################
automation:
  # Frontend Header Greeting
  - alias: Frontend Greeting
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: homeassistant
        event: start
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.frontend_greeting
        option: >
          {% if (states.sensor.time.state >= '00:00') and (states.sensor.time.state < '06:00') %}
            Gute Nacht
          {% elif (states.sensor.time.state >= '06:00') and (states.sensor.time.state < '12:00') %}
            Guten Morgen
          {% elif (states.sensor.time.state >= '12:00') and (states.sensor.time.state < '18:00') %}
            Guten Tag
          {% elif (states.sensor.time.state >= '18:00') and (states.sensor.time.state < '23:59') %}
            Guten Abend
          {% endif %}
  #####################################################################################################
  ## Automations that you should NOT touch!
  # State Change Automations used for device counting
  - alias: 'group state change'
    id: 'State changed'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_lighting','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_device_switches','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_binary_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_door_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_window_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_physical_devices','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_lights_on
        - sensor.current_devices_on
        - sensor.current_doors_open
        - sensor.current_windows_open
        - sensor.current_binary_sensors_on
        - sensor.physical_devices_failed

  # Popup More Info Boolean (used in popup windows to show the extra info view)
  - alias: light options boolean
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_boolean.light_options
        to: "on"
    action:
      - delay:
          seconds: 15
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.light_options

  # Theme Selector
  - alias: 'themes'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if is_state('input_select.theme_selector', 'Silver') %}
              Silver
            {% elif is_state('input_select.theme_selector', 'Space Gray') %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Sweet Pink') %}
              Sweet Pink
            {% elif is_state('input_select.theme_selector', 'Valentine') %}
              Valentine
            {% elif is_state('input_select.theme_selector', 'Disable (use theme per user)') %}
              Disable
            {% elif (is_state('sensor.anniversary_anniversary', '0')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Valentine
            {% elif (is_state('sun.sun', 'above_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Silver
            {% elif (is_state('sun.sun', 'below_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Auto') %}
              Space Gray
            {% endif %}
  # Box Shadow Selector
  - alias: input select beautifier box-shadow
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.box_shadow_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.box_shadow
        option: >
          {% if is_state('input_select.box_shadow_selector', 'None') %}
            none
          {% elif is_state('input_select.box_shadow_selector', 'Small') %}
            1px 1px 1px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Standard') %}
            2px 2px 2px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Medium') %}
            3px 3px 3px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Large') %}
            5px 5px 5px 0px rgba(0,0,0,0.75)
          {% endif %}
  # Border Radius Selector
  - alias: input select beautifier border-radius
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.border_radius_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.border_radius
        option: >
          {% if is_state('input_select.border_radius_selector', 'None') %}
            0px
          {% elif is_state('input_select.border_radius_selector', 'Small') %}
            6px
          {% elif is_state('input_select.border_radius_selector', 'Standard') %}
            12px
          {% elif is_state('input_select.border_radius_selector', 'Large') %}
            18px
          {% endif %}

#################################################
################### Sensors #####################
#################################################
sensor:
 ### Notification Badge Templates (needed for the badges to appear on buttons!)
### Please do NOT touch this!!!!

# Template All Lights
  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_lighting','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Devices
  - platform: template
    sensors:
      current_devices_on:
        friendly_name: All Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_device_switches','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Sensors
  - platform: template
    sensors:
      current_sensors_on:
        friendly_name: All Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_motion_smoke_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Sensors
  - platform: template
    sensors:
      current_binary_sensors_on:
        friendly_name: All Binary Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_binary_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Doors
  - platform: template
    sensors:
      current_doors_open:
        friendly_name: All Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_door_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Windows
  - platform: template
    sensors:
      current_windows_open:
        friendly_name: All Windows Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_window_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Scenes
  - platform: template
    sensors:
      current_scenes_on:
        friendly_name: All Scenes
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_scenes','entity_id'))|selectattr('state','eq','on')|list|count }}
# Template All Physical Devices
  - platform: template
    sensors:
      physical_devices_failed:
        friendly_name: All Physical Devices unknown or unavailable
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_physical_devices','entity_id'))|selectattr('state','in', ['unknown','unavailable', 'not_home'])|list|count }}