sensor:
  - platform: template
    sensors:
      tuer_wohnung:
        value_template: '{% if states.binary_sensor.tuer_wohnung %}
          {% if states.binary_sensor.tuer_wohnung.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Tür Wohnung'
  - platform: template
    sensors:
      count_lights:
        value_template: >
          {% set entities = [
            states.light.schlafzimmer,
            states.light.wohnzimmer,
            states.light.buero,
            states.light.ankleidezimmer ] %}
          {% set findstates = [ 'on', 'open' ] %}
          {{ entities | selectattr('state','in',findstates) | list | length }}
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

input_select:
  house_presence:
    name: Haus
    options:
      - Alle sind zu Hause
      - Ferien
      - Jemand ist zu Hause
      - Niemand ist zu Hause
    initial: Jemand ist zu Hause

media_player:
  -  platform: spotify
     client_id: !secret spotify_client_id
     client_secret: !secret spotify_api_key