sensor:        
  - platform: template
    sensors:
      count_lights:
        value_template: >
          {% set entities = [
            states.light.schlafzimmer,
            states.light.wohnzimmer,
            states.light.buero,
            states.light.ankleidezimmer ] %}
          {% set findstates = [ 'on', 'open' ] %}
          {{ entities | selectattr('state','in',findstates) | list | length }}

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

  - platform: darksky
    api_key: !secret darksky_api_key
    language: de
    name: Wetter Naefels
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - hourly_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 15

  - platform: darksky
    api_key: !secret darksky_api_key
    language: de
    name: Wetter Uznach
    longitude: 8.998294
    latitude: 47.219577
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - hourly_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 15

  - platform: darksky
    api_key: !secret darksky_api_key
    language: de
    name: Wetter Zurich
    longitude: 8.556287
    latitude: 47.414318
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - hourly_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 15

input_select:
  house_presence:
    name: Haus
    options:
      - Alle sind zu Hause
      - Ferien
      - Jemand ist zu Hause
      - Niemand ist zu Hause
    initial: Jemand ist zu Hause

media_player:
  -  platform: spotify
     client_id: !secret spotify_client_id
     client_secret: !secret spotify_api_key

# scene:
#   - name: Alle Weg
#     entities:
#       group.all_lights: off
#       switch.schalter_entfeuchter: on
#       remote.wohnzimmer: off
#       media_player.buero_musik_main: off
#   - name: Alles Aus
#     entities:
#       group.all_lights: off
#       switch.schalter_entfeuchter: off
#       remote.wohnzimmer: off
#       media_player.buero_musik_main: off
#       media_player.heos_5: paused

script:
  alle_weg:
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.all_lights
      - service: switch.turn_on
        data:
          entity_id: switch.schalter_entfeuchter
      - service: remote.turn_off
        data:
          entity_id: remote.wohnzimmer
      - service: media_player.turn_off
        data:
          entity_id: media_player.buero_musik_main
  alles_aus:
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.all_lights
      - service: switch.turn_on
        data:
          entity_id: switch.schalter_entfeuchter
      - service: remote.turn_off
        data:
          entity_id: remote.wohnzimmer
      - service: media_player.turn_off
        data:
          entity_id: media_player.buero_musik_main
      - service: media_player.media_pause
        data:
          entity_id: media_player.heos_5

circadian_lighting: