sensor:        
  - platform: template
    sensors:
      count_lights:
        value_template: >
          {% set entities = [
            states.light.schlafzimmer,
            states.light.wohnzimmer,
            states.light.buero,
            states.light.ankleidezimmer ] %}
          {% set findstates = [ 'on', 'open' ] %}
          {{ entities | selectattr('state','in',findstates) | list | length }}

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

input_select:
  house_presence:
    name: Haus
    options:
      - Alle sind zu Hause
      - Ferien
      - Jemand ist zu Hause
      - Niemand ist zu Hause
    initial: Jemand ist zu Hause

media_player:
  -  platform: spotify
     client_id: !secret spotify_client_id
     client_secret: !secret spotify_api_key

scene:
  - name: Alle Weg
    entities:
      group.all_lights: 
        state: false
      switch.schalter_entfeuchter: 
        state: true
      remote.wohnzimmer: 
        state: false
      media_player.buero_musik_main: 
        state: false
  - name: Alles Aus
    entities:
      group.all_lights: 
        state: false
      switch.schalter_entfeuchter: 
        state: false
      remote.wohnzimmer: 
        state: false
      media_player.buero_musik_main: 
        state: false
      media_player.heos_5:
        state: paused

circadian_lighting: