sensor:
  - platform: template
    sensors:
      tuer_kueche_balkon:
        value_template: '{% if states.binary_sensor.tuer_kueche_balkon %}
          {% if states.binary_sensor.tuer_kueche_balkon.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'T체r K체che Balkon'

      fenster_kueche:
        value_template: '{% if states.binary_sensor.fenster_kueche %}
          {% if states.binary_sensor.fenster_kueche.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Fenster K체che'

################################# Abwaschmaschine Verbrauch #################################
#  - platform: template
#    sensors:
#      dishwasher_power:
#        friendly_name: "Verbrauch Abwaschmaschine"
#        unit_of_measurement: "W"
#        value_template: "{{ states.switch.schalter_abwaschmaschine.attributes.current_power_w }}"

#switch:
################################# Abwaschmaschine Switch #################################
#  - platform: mystrom
#    host: !secret switch_dishwasher_ip
#    name: Schalter Abwaschmaschine

#input_select:
################################# Abwaschmaschine Status #################################
#  dishwasher_status:
#    name: Status Abwaschmaschine
#    options:
#      - Sauber
#      - Dreckig
#      - L채uft
#      - Trocknung
#    initial: Dreckig