media_player:
  -  platform: denonavr
     host: !secret denon_living_room_ip
     name: Denon AVR Wohnzimmer

  -  platform: kodi
     host: !secret kodi_ip
     name: Kodi Wohnzimmer
     username: !secret kodi_username
     password: !secret kodi_password

emulated_roku:
  host_ip: !secret host_ip
  listen_ports:
    - 8060:8060
    
remote:
  - platform: harmony
    name: Wohnzimmer
    host: !secret harmony_ip

light:
  - platform: group
    name: Wohnzimmer
    entities:
      - light.stehlampe_wohnzimmer_vorne
      - light.stehlampe_wohnzimmer_hinten

sensor:
  - platform: template
    sensors:
      harmony_activity:
        value_template: >
          {% if is_state("remote.wohnzimmer", 'on') %}
            {{ states.remote.wohnzimmer.attributes.current_activity }}
          {% else %}
            PowerOff
          {% endif %}
        friendly_name: Harmony Wohnzimmer Status

      fenster_wohnzimmer:
        value_template: '{% if states.binary_sensor.fenster_wohnzimmer %}
          {% if states.binary_sensor.fenster_wohnzimmer.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Fenster Wohnzimmer'

      tuer_wohnzimmer_balkon:
        value_template: '{% if states.binary_sensor.tuer_wohnzimmer_balkon %}
          {% if states.binary_sensor.tuer_wohnzimmer_balkon.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Tür Wohnzimmer Balkon'
