media_player:
  -  platform: denonavr
     host: !secret denon_living_room_ip
     name: Denon AVR Wohnzimmer

  -  platform: kodi
     host: !secret kodi_ip
     name: Kodi Wohnzimmer
     username: !secret kodi_username
     password: !secret kodi_password

emulated_roku:
  servers:
    - name: Roku Emu
      listen_port: 8060
      host_ip: !secret host_ip
      advertise_ip: !secret host_main_ip
      advertise_port: 8060

remote:
  - platform: harmony
    name: Wohnzimmer
    host: !secret harmony_ip

sensor:
  - platform: template
    sensors:
      harmony_activity:
        value_template: >
          {% if is_state("remote.wohnzimmer", 'on') %}
            {{ states.remote.wohnzimmer.attributes.current_activity }}
          {% else %}
            PowerOff
          {% endif %}
        friendly_name: Harmony Wohnzimmer Status

vacuum:
  -  platform: roomba
     host: !secret roomba_ip
     username: !secret roomba_user
     password: !secret roomba_key

