input_select:
  alarm_state:
    name: Status Alarmanlage
    options:
      - Ungesichert
      - Scharf ohne Bewegung
      - Scharf mit Bewegung
      - Einbrecher
    initial: Ungesichert
  last_motion:
    name: Letzte Bewegung
    options:
      - Schlafzimmer
      - Bad_klein
      - Buero
      - Ankleidezimmer
      - Bad_gross
      - Wohnzimmer

alarm_control_panel:
  - platform: manual
    name: Alarmanlage
    code: !secret alarm_panel_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0