switch:
  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/appdaemon
    name: AppDaemon
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/grafana
    name: Grafana
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/ha-dockermon
    name: ha-dockermon
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/hass
    name: Home Assistant
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/influxdb
    name: InfluxDB
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/mqtt
    name: MQTT Broker
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/deconz
    name: Deconz
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'  

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/letsencrypt
    name: Letsencrypt
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}' 

  - platform: rest
    username: !secret ha-dockermon_user
    password: !secret ha-dockermon_key
    resource: http://192.168.0.5:8126/container/glances
    name: Glances
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'     