# lovelace_gen

- title: Security
  icon: mdi:cctv
  path: security
  cards:
    - type: vertical-stack
      cards:
        - !include
          - '../templates/system_header.yaml'
          - content: Security
            icon: mdi:alert
            name: "[[[ if (states['alarm_control_panel.alarmanlage'].state == 'disarmed') return `Der Alarm ist aus`; else return `Der Alarm ist scharf!` ]]]"
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security[0] }}
            group: group.all_door_sensors
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security[1] }}
            group: group.all_window_sensors
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security[2] }}
            group: group.all_motion_sensors
        - !include ../includes/bottom-card.yaml