rooms:
  name: Zimmer
  icon: mdi:home
  entities:
    - group.office
    - group.dressroom
    - group.bedroom
    - group.livingroom
    - group.bathroom_large
    - group.bathroom_small
    - group.kitchen
office:
  name: Büro
  entities:
    - light.buero
    - binary_sensor.bewegung_buero
    - sensor.luftfeuchtigkeit_buero
    - sensor.temperatur_buero
    - sensor.lux_buero
    - sensor.fenster_buero
    - sensor.tuer_buero
dressroom:
  name: Ankleidezimmer
  entities:
    - light.ankleidezimmer
    - binary_sensor.bewegung_ankleidezimmer
    - sensor.luftfeuchtigkeit_ankleidezimmer
    - sensor.temperatur_ankleidezimmer
    - sensor.lux_ankleidezimmer
    - sensor.tuer_ankleidezimmer
    - sensor.fenster_ankleidezimmer
bedroom:
  name: Schlafzimmer
  entities:
    - light.schlafzimmer
    - binary_sensor.bewegung_schlafzimmer
    - sensor.luftfeuchtigkeit_schlafzimmer
    - sensor.temperatur_schlafzimmer
    - sensor.lux_schlafzimmer
    - sensor.tuer_schlafzimmer
    - sensor.fenster_schlafzimmer
    - switch.schalter_entfeuchter
livingroom:
  name: Wohnzimmer
  entities:
    - light.wohnzimmer
    - vacuum.roomba
    - remote.wohnzimmer
    - sensor.fenster_wohnzimmer
    - sensor.tuer_wohnzimmer_balkon
kitchen:
  name: Küche
  entities:
    - sensor.tuer_kueche_balkon
    - sensor.fenster_kueche
    - sensor.tuer_reduit
bathroom_large:
  name: Badzimmer gross
  entities:
    - sensor.tuer_bad_gross
    - sensor.fenster_bad_gross
bathroom_small:
  name: Badzimmer klein
  entities:
    - sensor.tuer_bad_klein
    - binary_sensor.bewegung_bad_klein
    - sensor.temperatur_bad_klein
    - sensor.luftfeuchtigkeit_bad_klein
    - sensor.lux_bad_klein
    - sensor.bad_klein_multisensor_battery
