include:
  entities:
    - input_select.dimitri_presence
    - input_boolean.charging_phone_dimitri
    - remote.wohnzimmer
    - device_tracker.dimitri_pc
    - sensor.nacht_sensor
    - input_boolean.sleep_mode
    - binary_sensor.dimitri_home_not_sleeping
    - binary_sensor.lights_off_sleeping
    - binary_sensor.lights_off_not_sleeping
    - binary_sensor.dimitri_phone_charging_sleeping
    - binary_sensor.dimitri_phone_charging_not_sleeping
    - binary_sensor.remote_off_sleeping
    - binary_sensor.remote_off_not_sleeping
    - binary_sensor.night_sleeping
    - binary_sensor.night_not_sleeping